#!/bin/bash
# generate-checksums.sh — Generate CHECKSUMS.sha256 for skills
# Run after any skill update
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
SKILLS_DIR="$REPO_DIR/skills"
CHECKSUM_FILE="$SKILLS_DIR/CHECKSUMS.sha256"

if [ ! -d "$SKILLS_DIR" ]; then
  echo "ERROR: skills/ not found at $SKILLS_DIR"
  exit 1
fi

echo "Generating checksums for skills/..."
echo "# Auto-generated by generate-checksums.sh" > "$CHECKSUM_FILE"
echo "# Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$CHECKSUM_FILE"
echo "#" >> "$CHECKSUM_FILE"

COUNT=0
find "$SKILLS_DIR" -type f -name "*.md" -o -name "*.sh" -o -name "*.py" -o -name "*.js" -o -name "*.json" | sort | while read -r file; do
  rel_path="${file#$SKILLS_DIR/}"
  hash=$(sha256sum "$file" 2>/dev/null | awk '{print $1}')
  if [ -n "$hash" ]; then
    echo "$hash  $rel_path" >> "$CHECKSUM_FILE"
    COUNT=$((COUNT + 1))
  fi
done

TOTAL=$(wc -l < "$CHECKSUM_FILE" | tr -d ' ')
echo "Generated $TOTAL checksums in $CHECKSUM_FILE"
